language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: NumberParserCore/NumberParserCore.sln
install:
  - cd NumberParserCore && dotnet restore
script:
  - cd NumberParserCore && dotnet build
  - cd NumberParserCore && dotnet test
after_success:
  - echo dotnet test succeeded
after_failure:
  - echo dotnet test failed