dist: trusty
sudo: false
language: csharp
solution: NumberParserCore/NumberParserCore.sln
mono: none
dotnet: 2.2.103
install:
  - cd NumberParserCore && dotnet restore
script:
  - cd NumberParserCore && dotnet build
  - cd NumberParserCore && dotnet test
after_success:
  - echo dotnet test succeeded
after_failure:
  - echo dotnet test failed